services:
  table-diff-sample-db:
    image: mysql:8.0
    ports:
      - 19000:3306
    volumes:
      - ./docker/mysql/init.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: table-diff-sample
      MYSQL_USER: user
      MYSQL_PASSWORD: password
